### PR TITLE
Fixed result file content.

### LINKED ISSUE #45: [BE]: result file content is returned with incorrect Content-Type
1. Validate some file
2. Call `GET /api/files/{validationResultId}` without any `Accept` header.

**Bug**: response is returned with `Content-Type: application/octet-stream`
**Expected**: response content type to be `application/json`

### PR DESCRIPTION
**Pull request by RomaPrograms**
Closes #45

### CODE REVIEW

File: worker/src/main/java/org/verapdf/webapp/worker/listener/ExecutableTaskWorker.java [hunk 1]
```diff
@@ -128,7 +128,7 @@ private File getFileToProcess(UUID fileId) throws VeraPDFWorkerException {
 
 	private StoredFileDTO saveReportFile(ValidationReport validationReport, UUID fileId)
 			throws VeraPDFWorkerException {
-		File reportFile = new File(workDir, "report-" + fileId);
+		File reportFile = new File(workDir, "report-" + fileId + ".json");
```
Comment (BezrukovM) [inline worker/src/main/java/org/verapdf/webapp/worker/listener/ExecutableTaskWorker.java:131]: This should not be done. The content type header should be set during the request from client. While we are not required to use some sort of extension for our files
